title: PyTorch Lightning CIFAR10 ~94% Baseline Tutorial
author: PL team
created: 2020-12-21
updated: 2021-06-07
license: CC
description: >
  Train a Resnet to 94% accuracy on Cifar10!
requirements:
  - torchvision
  - lightning-bolts
accelerator:
  - GPU
