name: CI complete testing

# see: https://help.github.com/en/actions/reference/events-that-trigger-workflows
on:  # Trigger the workflow on push to master
  push: {}
  # FIXME
  #  branches: [main]

jobs:
  generate-ipynb:
    runs-on: ubuntu-20.04
    # Timeout: https://stackoverflow.com/a/59076067/4521646
    timeout-minutes: 45

    steps:
    - uses: actions/checkout@v2
      with:
        # fetch all history for all branches and tags
        fetch-depth: 0
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Get pip cache
      id: pip-cache
      run: python -c "from pip._internal.locations import USER_CACHE_DIR; print('::set-output name=dir::' + USER_CACHE_DIR)"

    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ${{ steps.pip-cache.outputs.dir }}
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        pip --version
        pip install --requirement requirements.txt
        pip list
      shell: bash

    - name: Process folders
      run: |
        head=$(git rev-parse origin/main)
        git diff --name-only $head --output=master-diff.txt
        python .actions/filter-folders.py master-diff.txt changed_folders.txt
        while IFS= read -r line; do
            bash .actions/generate-ipynb.sh $line
        done <<< $(cat changed_folders.txt)
      shell: bash
